version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:7.17.16
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - skywalking-net
    restart: always

  oap:
    image: apache/skywalking-oap-server:10.2.0
    container_name: skywalking-oap
    depends_on:
      - elasticsearch
    ports:
      - "11800:11800" # SkyWalking gRPC
      - "12800:12800" # SkyWalking HTTP
      - "9411:9411" # SkyWalking HTTP
    environment:
      SW_STORAGE: elasticsearch
      SW_STORAGE_ES_CLUSTER_NODES: elasticsearch:9200
      SW_CONFIGURATION_PRINT: "true"
      SW_OTEL_RECEIVER: default
      SW_OTEL_RECEIVER_ENABLED_HANDLERS: otlp-traces
      SW_RECEIVER_ZIPKIN: default
      SW_QUERY_ZIPKIN: default
    volumes:
        - ./config/application.yml:/skywalking/config/application.yml
    restart: always
    networks:
      - skywalking-net

  ui:
    image: apache/skywalking-ui:10.2.0
    container_name: skywalking-ui
    ports:
      - "8080:8080"
    environment:
      SW_OAP_ADDRESS: http://oap:12800
    depends_on:
      - oap
    restart: always
    networks:
      - skywalking-net

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.89.0
    container_name: otel-collector
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    command:
      --config /etc/otel-collector-config.yaml
    ports:
      - "4317:4317"  # OTLP gRPC receiver
      - "4318:4318"  # OTLP HTTP receiver
    depends_on:
      - oap
    networks:
      - skywalking-net

networks:
  skywalking-net:
    driver: bridge
