version: '3.8'

services:
  oap:
    image: apache/skywalking-oap-server:10.2.0
    container_name: skywalking-oap
    ports:
      - "11800:11800" # SkyWalking gRPC
      - "12800:12800" # SkyWalking HTTP
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    environment:
      SW_STORAGE: h2
      SW_RECEIVER_OTLP_ENABLED: "true"
      SW_OTLP_RECEIVER_GRPC_PORT: 4317
      SW_OTLP_RECEIVER_HTTP_PORT: 4318
    restart: always
    networks:
      - skywalking-net

  ui:
    image: apache/skywalking-ui:10.2.0
    container_name: skywalking-ui
    ports:
      - "8080:8080"
    environment:
      SW_OAP_ADDRESS: http://oap:12800
    depends_on:
      - oap
    restart: always
    networks:
      - skywalking-net

networks:
  skywalking-net:
    driver: bridge